import { Currency, CurrencySymbol } from './types';

const currencies: Record<string, CurrencySymbol> = {
  [Currency.ALL]: { unicode: '4c, 65, 6b', symbol: undefined },
  [Currency.AFN]: { unicode: '60b', symbol: undefined },
  [Currency.ARS]: { unicode: '24', symbol: undefined },
  [Currency.AWG]: { unicode: '192', symbol: undefined },
  [Currency.AUD]: { unicode: '24', symbol: undefined },
  [Currency.AZN]: { unicode: '20bc', symbol: undefined },
  [Currency.BSD]: { unicode: '24', symbol: undefined },
  [Currency.BBD]: { unicode: '24', symbol: undefined },
  [Currency.BYN]: { unicode: '42, 72', symbol: undefined },
  [Currency.BZD]: { unicode: '42, 5a, 24', symbol: undefined },
  [Currency.BMD]: { unicode: '24', symbol: undefined },
  [Currency.BOB]: { unicode: '24, 62', symbol: undefined },
  [Currency.BAM]: { unicode: '4b, 4d', symbol: undefined },
  [Currency.BWP]: { unicode: '50', symbol: undefined },
  [Currency.BGN]: { unicode: '43b, 432', symbol: undefined },
  [Currency.BRL]: { unicode: '52, 24', symbol: undefined },
  [Currency.BND]: { unicode: '24', symbol: undefined },
  [Currency.KHR]: { unicode: '17db', symbol: undefined },
  [Currency.CAD]: { unicode: '24', symbol: undefined },
  [Currency.KYD]: { unicode: '24', symbol: undefined },
  [Currency.CLP]: { unicode: '24', symbol: undefined },
  [Currency.CNY]: { unicode: 'a5', symbol: undefined },
  [Currency.COP]: { unicode: '24', symbol: undefined },
  [Currency.CRC]: { unicode: '20a1', symbol: undefined },
  [Currency.HRK]: { unicode: '6b, 6e', symbol: undefined },
  [Currency.CUP]: { unicode: '20b1', symbol: undefined },
  [Currency.CZK]: { unicode: '4b, 10d', symbol: undefined },
  [Currency.DKK]: { unicode: '6b, 72', symbol: undefined },
  [Currency.DOP]: { unicode: '52, 44, 24', symbol: undefined },
  [Currency.XCD]: { unicode: '24', symbol: undefined },
  [Currency.EGP]: { unicode: 'a3', symbol: undefined },
  [Currency.SVC]: { unicode: '24', symbol: undefined },
  [Currency.EUR]: { unicode: '20ac', symbol: undefined },
  [Currency.FKP]: { unicode: 'a3', symbol: undefined },
  [Currency.FJD]: { unicode: '24', symbol: undefined },
  [Currency.GHS]: { unicode: 'a2', symbol: undefined },
  [Currency.GIP]: { unicode: 'a3', symbol: undefined },
  [Currency.GTQ]: { unicode: '51', symbol: undefined },
  [Currency.GGP]: { unicode: 'a3', symbol: undefined },
  [Currency.GYD]: { unicode: '24', symbol: undefined },
  [Currency.HNL]: { unicode: '4c', symbol: undefined },
  [Currency.HKD]: { unicode: '24', symbol: undefined },
  [Currency.HUF]: { unicode: '46, 74', symbol: undefined },
  [Currency.ISK]: { unicode: '6b, 72', symbol: undefined },
  [Currency.IDR]: { unicode: '52, 70', symbol: undefined },
  [Currency.IRR]: { unicode: 'fdfc', symbol: undefined },
  [Currency.IMP]: { unicode: 'a3', symbol: undefined },
  [Currency.ILS]: { unicode: '20aa', symbol: undefined },
  [Currency.JMD]: { unicode: '4a, 24', symbol: undefined },
  [Currency.JPY]: { unicode: 'a5', symbol: undefined },
  [Currency.JEP]: { unicode: 'a3', symbol: undefined },
  [Currency.KZT]: { unicode: '43b, 432', symbol: undefined },
  [Currency.KPW]: { unicode: '20a9', symbol: undefined },
  [Currency.KRW]: { unicode: '20a9', symbol: undefined },
  [Currency.KGS]: { unicode: '43b, 432', symbol: undefined },
  [Currency.LAK]: { unicode: '20ad', symbol: undefined },
  [Currency.LBP]: { unicode: 'a3', symbol: undefined },
  [Currency.LRD]: { unicode: '24', symbol: undefined },
  [Currency.MKD]: { unicode: '434, 435, 43d', symbol: undefined },
  [Currency.MYR]: { unicode: '52, 4d', symbol: undefined },
  [Currency.MUR]: { unicode: '20a8', symbol: undefined },
  [Currency.MXN]: { unicode: '24', symbol: undefined },
  [Currency.MNT]: { unicode: '20ae', symbol: undefined },
  [Currency.MZN]: { unicode: '4d, 54', symbol: undefined },
  [Currency.NAD]: { unicode: '24', symbol: undefined },
  [Currency.NPR]: { unicode: '20a8', symbol: undefined },
  [Currency.ANG]: { unicode: '192', symbol: undefined },
  [Currency.NZD]: { unicode: '24', symbol: undefined },
  [Currency.NIO]: { unicode: '43, 24', symbol: undefined },
  [Currency.NGN]: { unicode: '20a6', symbol: undefined },
  [Currency.NOK]: { unicode: '6b, 72', symbol: undefined },
  [Currency.OMR]: { unicode: 'fdfc', symbol: undefined },
  [Currency.PKR]: { unicode: '20a8', symbol: undefined },
  [Currency.PAB]: { unicode: '42, 2f, 2e', symbol: undefined },
  [Currency.PYG]: { unicode: '47, 73', symbol: undefined },
  [Currency.PEN]: { unicode: '53, 2f, 2e', symbol: undefined },
  [Currency.PHP]: { unicode: '20b1', symbol: undefined },
  [Currency.PLN]: { unicode: '7a, 142', symbol: undefined },
  [Currency.QAR]: { unicode: 'fdfc', symbol: undefined },
  [Currency.RON]: { unicode: '6c, 65, 69', symbol: undefined },
  [Currency.RUB]: { unicode: '20bd', symbol: undefined },
  [Currency.SHP]: { unicode: 'a3', symbol: undefined },
  [Currency.SAR]: { unicode: 'fdfc', symbol: undefined },
  [Currency.RSD]: { unicode: '414, 438, 43d, 2e', symbol: undefined },
  [Currency.SCR]: { unicode: '20a8', symbol: undefined },
  [Currency.SGD]: { unicode: '24', symbol: undefined },
  [Currency.SBD]: { unicode: '24', symbol: undefined },
  [Currency.SOS]: { unicode: '53', symbol: undefined },
  [Currency.ZAR]: { unicode: '52', symbol: undefined },
  [Currency.XOF]: { unicode: undefined, symbol: 'CAF' },
  [Currency.LKR]: { unicode: '20a8', symbol: undefined },
  [Currency.SEK]: { unicode: '6b, 72', symbol: undefined },
  [Currency.CHF]: { unicode: '43, 48, 46', symbol: undefined },
  [Currency.SRD]: { unicode: '24', symbol: undefined },
  [Currency.SYP]: { unicode: 'a3', symbol: undefined },
  [Currency.TWD]: { unicode: '4e, 54, 24', symbol: undefined },
  [Currency.THB]: { unicode: 'e3f', symbol: undefined },
  [Currency.TTD]: { unicode: '54, 54, 24', symbol: undefined },
  [Currency.TVD]: { unicode: '24', symbol: undefined },
  [Currency.UAH]: { unicode: '20b4', symbol: undefined },
  [Currency.GBP]: { unicode: 'a3', symbol: undefined },
  [Currency.USD]: { unicode: '24', symbol: undefined },
  [Currency.UYU]: { unicode: '24, 55', symbol: undefined },
  [Currency.UZS]: { unicode: '43b, 432', symbol: undefined },
  [Currency.VEF]: { unicode: '42, 73', symbol: undefined },
  [Currency.VND]: { unicode: '20ab', symbol: undefined },
  [Currency.YER]: { unicode: 'fdfc', symbol: undefined },
  [Currency.ZWD]: { unicode: '5a, 24', symbol: undefined },
  [Currency.MAD]: { unicode: '2e, 62f, 2e, 645', symbol: undefined },
};

export default currencies;
